version: '3'

env:
  ENV: infra/envs

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
 compose-local:
    dir: ./infra
    cmds:
      - docker compose pull
      - docker compose up -d
 redoc-api:
    vars:
      OPENAPI_DIR: ./api/openapi
      DIST_DIR: ./dist
    dir: ./api/openapi
    sources:
      - academic.yaml
      - attendance.yaml
      - student.yaml
      - teacher.yaml
      - user.yaml
    cmds:
      - for: sources
        cmd: redocly bundle {{.ITEM}} -o {{joinPath .DIST_DIR .ITEM}}
      - cmd: redocly join dist/academic.yaml dist/attendance.yaml dist/student.yaml dist/teacher.yaml dist/user.yaml -o {{joinPath .DIST_DIR "school.yaml"}}
 generate-api:
     deps: ["redoc-api"]
     cmds:
       - cmd: bazelisk build //api/openapi:generate
       - cmd: yes | cp -rf ./bazel-bin/api/openapi/school.gen.go ./api/openapi
 bazel:
     cmds:
       - bazelisk run //:gazelle
       - bazelisk run //:gazelle-update-repos
       - bazelisk build //...