openapi: "3.0.0"
info:
  version: 1.0.0
  title: School APP - Attendance Management
  license:
    name: MIT
servers:
  - url: http://localhost:8080
security:
  - bearerAuth: []
paths:
  /academic/years/{ayid}/classes/{cid}/attendances:
   post:
     summary: record attendance
     operationId: recordAttendance
     tags:
       - recordAttendance
     parameters:
       - in: path
         name: ayid
         schema:
          type: string
         required: true
       - in: path
         name: cid
         schema:
          type: string
         required: true
     requestBody:
       content:
         application/json:
          schema:
           $ref: '#/components/schemas/RecordAttendanceReq'
     responses:
       '201':
        description: academicYear successfully created
        content:
          application/json:
           schema:
            $ref: 'meta.yaml#/components/schemas/EmptyResponse'
       default:
        description: unexpected errors
        content:
          application/json:
           schema:
            $ref: './meta.yaml#/components/schemas/ErrorResponse'
    
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      $ref: 'meta.yaml#/components/securitySchemes/bearerAuth'
  schemas:
   AttendanceType:
    type: string
    enum:
      - SAKIT
      - TANPA_KETERANGAN
      - HADIR
      - IZIN
   AttendanceItem:
    type: object
    properties:
      student_id:
       type: string
      recorded_date:
       type: string
       format: date
      at:
       $ref: '#/components/schemas/AttendanceType'
   RecordAttendanceReq:
    type: object
    properties:
      items:
       type: array
       items:
        $ref: "#/components/schemas/AttendanceItem"