openapi: 3.0.0
info:
  version: 1.0.0
  title: School APP - Academic Year Management
  license:
    name: MIT
servers:
  - url: http://localhost:8080
security:
  - bearerAuth: []
paths:
  /teachers:
    post:
      summary: Register a new teacher
      operationId: registerTeacher
      tags:
        - registerTeacher
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterTeacherReq'
      responses:
        '201':
          description: Teacher successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Teacher'
        default:
          description: unexpected errors
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Teacher:
      type: object
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: string
        nik:
          type: string
        gender:
          $ref: '#/components/schemas/Gender'
        religion:
          $ref: '#/components/schemas/Religion'
    RegisterTeacherReq:
      type: object
      properties:
        user_id:
          type: string
        nik:
          type: string
        gender:
          $ref: '#/components/schemas/Gender'
        religion:
          $ref: '#/components/schemas/Religion'
    Gender:
      type: string
      enum:
        - MALE
        - FEMALE
    Religion:
      type: string
      enum:
        - ISLAM
        - PROTESTAN
        - KRISTEN
        - HINDU
        - BUDDHA
        - KONGHUCU
    ErrorResponse:
      type: object
      properties:
        httpCode:
          type: integer
          description: http status error code
        errorCode:
          type: string
          description: error code
        errorMessage:
          type: string
          description: error message
