openapi: "3.0.0"
info:
  version: 1.0.0
  title: School APP - Academic Year Management
  license:
    name: MIT
servers:
  - url: http://localhost:8080
security:
  - bearerAuth: []
paths:
  /teachers:
   post:
     summary: Register a new teacher
     operationId: registerTeacher
     tags:
       - registerTeacher
     requestBody:
       content:
         application/json:
          schema:
           $ref: '#/components/schemas/RegisterTeacherReq'
     responses:
       '201':
        description: Teacher successfully created
        content:
          application/json:
           schema:
            $ref: '#/components/schemas/Teacher'
       default:
        description: unexpected errors
        content:
          application/json:
           schema:
            $ref: './meta.yaml#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      $ref: 'meta.yaml#/components/securitySchemes/bearerAuth'
  schemas:
   Teacher:
    type: object
    properties:
      id: 
       type: string
       format: uuid
      user_id: 
       type: string
       format: string
      nik:
       type: string
      gender:
       $ref: './meta.yaml#/components/schemas/Gender'
      religion:
       $ref: './meta.yaml#/components/schemas/Religion'
   RegisterTeacherReq:
    type: object
    properties:
      user_id:
       type: string
      nik:
       type: string
      gender:
       $ref: './meta.yaml#/components/schemas/Gender'
      religion:
       $ref: './meta.yaml#/components/schemas/Religion'
       
     
    