// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicYear struct {
	ID        pgtype.UUID
	Label     string
	CreatedAt pgtype.Timestamptz
}

type AttendanceType struct {
	ID        pgtype.UUID
	Label     string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type StudentAttendance struct {
	ID               pgtype.UUID
	StudentClassID   pgtype.UUID
	Attend           pgtype.Bool
	AttendanceDate   pgtype.Date
	AttendanceTypeID pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CreatedBy        pgtype.Text
	UpdatedBy        pgtype.Text
}

type StudentClass struct {
	ID               pgtype.UUID
	StudentID        pgtype.UUID
	ClassLabel       string
	AcademicYearID   pgtype.UUID
	DeactivateReason pgtype.Text
	OwnerID          string
	CreatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}
